name: Continuous Deployment
on:
  push:
    branches:
      - 'main'

concurrency:
  group: cd-${{ github.head_ref }}
  cancel-in-progress: true
  


jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise up
      - run: mise run website:deploy