name: Website

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: website-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: jdx/mise-action@v2
        with:
            experimental: true
      - run: mise up
      - run: mise run website:build